import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar/SideBar";
import TopBar from "@/components/TopBar/TopBar";
import styles from "./main.module.css";

// import { ThemeProvider  } from "next-themes"

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-[#E5F4FB]`}>
        <div className={styles.parent}>
          <header className={`${styles.topBar} border-b`}>
            <TopBar />
          </header>

          <aside className={`${styles.sideBar} bg-primary`}>
            <SideBar />
          </aside>

          <main className={styles.main}>{children}</main>

          <footer className={`${styles.footer} border-t`}>I am footer</footer>
        </div>
      </body>
    </html>
  );
}
{
  /* <html lang="en">
<body className={`${roboto.className} bg-[#E5F4FB] flex `}>
  <div className="h-screen bg-primary  w-[230px] flex flex-col">
    <TopBar/>
    <SideBar />
  </div>
  {children}
</body>
</html> */
}
