import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/custom/SideBar/SideBar";
import TopBar from "@/custom/TopBar/TopBar";
// import { ThemeProvider  } from "next-themes"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#e5f4fb] `}>
      
        <div className="">
          <TopBar />
        </div>
        <div className="flex gap-3">
          <SideBar />{children}
        </div>
        
        
      </body>
    </html>
  );
}
